### Register a new user (JobSeeker)
POST https://forjobseeker-rv9r.onrender.com/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "jay@2019PT",
  "role": "JOBSEEKER",
  "firstName": "John",
  "lastName": "Doe",
  "phone": "1234567890",
  "jobFieldId": "8c40a4e7-f843-40c7-bec8-8a3ab263d2b0", 
  "maxQualification": "Bachelor's Degree",
  "yearsOfExperience": "5"
}

### Register a new user (Company)
POST https://forjobseeker-rv9r.onrender.com/api/auth/register
Content-Type: application/json

{
  "email": "company21@example.com",
  "password": "password123",
  "role": "COMPANY",
  "companyName": "Tech Corp",
  "website": "https://techcorp.com",
  "country": "USA",
  "businessEmail": "info@techcorp.com",
  "licenseNumber": "ABC123455"
}

### Login user
POST https://forjobseeker-rv9r.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "jobseeker@example.com",
  "password": "password123"
}

### Reset password while logged in
PUT http://localhost:5000/api/auth/reset-password
Content-Type: application/json
Authorization: Bearer <RESET_TOKEN>

{
  "oldPassword": "password123",
  "newPassword": "newpassword456"
}

### Forgot password
POST http://localhost:5000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "jobseeker@example.com"
}

### Reset password using token
PUT http://localhost:5000/api/auth/reset-password-with-token
Content-Type: application/json

{
  "token": "<RESET_TOKEN>",
  "newPassword": "newpassword456"
}
